name: Build and push container image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  container:
    name: container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: Lightprotocol/solana

      - name: Solana
        uses: docker/build-push-action@v4
        with:
          context: solana
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            ARG ANCHOR_TAG=v0.26.0
            ARG SOLANA_BRANCH=v1.15
            ARG SOLANA_PROGRAM_LIBRARY_TAG=account-compression-v0.1.8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Devcontainer
        uses: docker/build-push-action@v4
        with:
          context: devcontainer
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BASE_IMAGE=ghcr.io/lightprotocol/solana:${{ steps.meta.outputs.version }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
